### ISSUE TITLE
test: red CI — _make_minimal_agent fixture missing team_id (BaseAgent has no attribute 'team_id')

### ISSUE THREAD

**Issue by gpiroux** [b12consulting/akgentic-agent#59]
## Problem

`master` CI is red: 10 tests in `tests/agent/test_agent_coverage.py` (`TestReceiveAgentMessage`, `TestSlashCommandDispatch`) fail with:

```
AttributeError: 'BaseAgent' object has no attribute 'team_id'
```

## Root cause

`receiveMsg_AgentMessage` logs `[{self.config.name}-{self.team_id}]` (`src/akgentic/agent/agent.py:467`, introduced in #56 "redact message content from agent INFO logs"). `self.team_id` is a normal attribute set by core `Akgent.__init__`, so a real agent always has it.

The unit-test helper `_make_minimal_agent` builds a **partial** agent via `object.__new__(BaseAgent)` and sets a curated set of attributes (`_command_registry`, `_react_agent`, `config`, …) but **not `team_id`**. Every test that routes through `receiveMsg_AgentMessage` (the receive path and the `/compact`·`/clear` slash-command dispatch) therefore hits the missing attribute.

Production is correct — the fixture under-specified the agent.

## Fix

Set `team_id` on the fixture (a real agent always has it via `Akgent.__init__` / `createActor`). Test-only change.

## Verification

- Full `akgentic-agent` suite: 109 passed (the 10 failures gone).
- `ruff check` clean.
- `mypy src/` unaffected (change is test-only; `team_id` is a known typed attribute).
